name: Release Node.js SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the Node.js SDK that you would like to release"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Fern CLI
        run: npm install -g fern-api

      - name: Generate Node.js SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          fern generate --group ts-sdk --version ${{ inputs.version }} --log-level debug
